### PR TITLE
Optimize check-in overview card on smaller screens

### PR DESCRIPTION
**Pull request by timoschwarzer**
Base layout:
image

If there's not enough space, things wrap around:
image

### CODE REVIEW

**Comment by jheubuch** [comment]
I'll have a look on this on the next view days. I like the approach but I think it can get a bit optimized from the layout :)

**Comment by timoschwarzer** [comment]
👍 I'm also not 100% satisfied with the result yet 😅

**Comment by jheubuch** [comment]
Since I built the whole thing new with Jetpack Compose (and I tested it with large screen settings), I would close this PR because it is already fixed :)

image

**Comment by timoschwarzer** [comment]
Looks great! 🙌

**Pull request closed without merging**
